<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/03_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

tensor_from_list = torch.tensor([1,2,3,4,5])
tensor_from_tuple = torch.tensor((6,7,8,9,10))
print(tensor_from_list)
print(tensor_from_tuple)

tensor([1, 2, 3, 4, 5])
tensor([ 6,  7,  8,  9, 10])


In [4]:
tensor_from_numpy = torch.tensor(np.array([11,12,13,14,15]))
print(tensor_from_numpy)

tensor([11, 12, 13, 14, 15])


In [5]:
tens_emp = torch.empty(3,4)
tens_zeros = torch.zeros(3,4)
tens_ones = torch.ones(3,4)

In [9]:
tens_rand = torch.rand(4,5) # rand - >0, dimensions specified
tens_randn = torch.randn(4,5) # both <0 and >0
tens_randint = torch.randint(5,10,(4,5)) # numbers from 5 to 10 in a 2d dimension
print(tens_rand)
print(tens_randn)
print(tens_randint)

tensor([[0.0700, 0.2654, 0.6683, 0.8174, 0.9475],
        [0.2211, 0.5377, 0.2427, 0.4954, 0.0563],
        [0.6621, 0.3262, 0.3098, 0.3914, 0.8225],
        [0.1346, 0.4987, 0.5966, 0.4512, 0.8650]])
tensor([[ 0.2628, -1.6036, -1.1447, -0.6732, -1.0400],
        [ 0.4965, -0.1952, -0.0758, -0.2320, -0.1785],
        [ 0.3552,  0.7065,  0.3431,  0.6074,  0.3217],
        [-0.5074, -0.2134, -2.0011,  2.1371, -1.6579]])
tensor([[7, 8, 5, 6, 7],
        [8, 6, 9, 9, 7],
        [9, 9, 8, 7, 5],
        [8, 6, 8, 8, 6]])


In [12]:
# create tensor with similar properties, initialize a tensor of zeros, so simply add _like to get similar properties as tensor in parentheses
tensor_alike = torch.zeros_like(tens_randint)
tensor_alike

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])