<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/03_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [8]:
# Creating tensors like other tensors (_like)
start_tens = torch.ones(2,5)
start_tens

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
torch.manual_seed(111)
rand_tens = torch.rand_like(start_tens)
rand_tens

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [10]:
ones_tens = torch.ones_like(rand_tens)
ones_tens

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
end_tens = torch.randint_like(ones_tens, -1, 10)
end_tens

tensor([[2., 6., 5., 6., 0.],
        [5., 3., 9., 5., 0.]])

In [13]:
end_fr_tens = torch.full_like(end_tens, 7)
end_fr_tens

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])