<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/03_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [9]:
# torch.rand() selects values from a uniform distribution on the interval [0-1] (all numbers are equally likely to occur)
torch.manual_seed(41) # to get same results
torch.rand(3,3)

tensor([[0.2364, 0.2266, 0.8005],
        [0.1692, 0.2650, 0.7720],
        [0.1282, 0.7452, 0.8045]])

In [13]:
# torch.randn() selects values from a standard normal distribution (some numbers are likely to occur than others)
torch.randn(4,4)

tensor([[ 1.4119,  1.0538, -0.2638, -2.6467],
        [ 0.8843, -1.5721,  0.6455, -0.8498],
        [-0.6791,  0.4650, -0.0321,  0.1085],
        [ 0.4343,  1.0954,  0.1730, -0.6855]])

In [11]:
# torch.randint() to have specified range numbers can be
torch.randint(-1,10,(4,4))

tensor([[ 6,  2,  6,  6],
        [ 6,  2,  0,  3],
        [ 8,  4, -1,  7],
        [ 0,  9,  9,  6]])