<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/04_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Linear Algebra operations

In [2]:
# Compute the dot product (scalar) of two 1d tensors

tens1 = torch.tensor([1,2,3])
tens2 = torch.tensor([4,5,6])

dot_product = torch.matmul(tens1, tens2) # multiplies the numbers corresponding to same indexes and sums them up
dot_product

tensor(32)

In [4]:
# Compute the matrix-matrix product (2D tensor) of two 2d tensors

tens1_2d = torch.tensor([[1,2,3],[-1,-2,-3]]) # (2,3)
tens2_2d = torch.tensor([[-1,-2],[4,5],[4,5]]) # (3,2)

result_2d_tensor = torch.matmul(tens1_2d, tens2_2d)
result_2d_tensor

tensor([[ 19,  23],
        [-19, -23]])

In [7]:
# Compute the matrix of 5 2d-tensors

tens_1 = torch.randn(2,3)
tens_2 = torch.randn(3,4)
tens_3 = torch.randn(4,5)
tens_4 = torch.randn(5,6)
tens_5 = torch.randn(6,7)
torch.linalg.multi_dot((tens_1,tens_2,tens_3,tens_4,tens_5))

tensor([[  6.9190,   7.9797,   7.5376,  -6.1533,   3.3462,   3.1742,   7.7010],
        [-14.4370,  -6.8523,  10.3348,   7.3386, -12.1354,  12.2704,   5.0750]])

In [8]:
# Computing eigenvalues and eigenvectors

a = torch.randn(4,4)

eigenvalues, eigenvectors = torch.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

tensor([ 0.7132+0.0000j, -0.7947+1.3278j, -0.7947-1.3278j, -1.3093+0.0000j])
tensor([[ 0.1142+0.0000j,  0.0261+0.4235j,  0.0261-0.4235j,  0.2111+0.0000j],
        [-0.5251+0.0000j,  0.8328+0.0000j,  0.8328-0.0000j, -0.2498+0.0000j],
        [ 0.8202+0.0000j,  0.2713+0.2224j,  0.2713-0.2224j, -0.1346+0.0000j],
        [ 0.1962+0.0000j, -0.0490-0.0305j, -0.0490+0.0305j,  0.9354+0.0000j]])
