<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/04_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [3]:
one_dim_tensor = torch.tensor([1,2,3,4,5,6,7,8])
# print one element from 1-dim tensor
print(one_dim_tensor[2].item())

3


In [10]:
# slicing 1-dim tensor(elements 2-4)
one_dim_tensor[1:4]

tensor([2, 3, 4])

In [12]:
# indexing 2-dim tensor
two_dim_tensor = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18], [19,20,21,22,23,24]])
two_dim_tensor[1][3].item()

10

In [15]:
# slicing 2-dim tensor
print(two_dim_tensor[0,0:3]) # first 3 elements of the first row
print(two_dim_tensor[1,0:4]) # first 4 elements of the second row

tensor([1, 2, 3])
tensor([ 7,  8,  9, 10])


In [17]:
# use indexing to extract the data that meets some criteria
two_dim_tensor[two_dim_tensor<17]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
# combine tensors
torch.stack((two_dim_tensor, two_dim_tensor))

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [24]:
# split tensors
tens1, tens2, tens3, test_4 = torch.unbind(two_dim_tensor) # splits accordingly to the number of rows
print(tens1)

tensor([1, 2, 3, 4, 5, 6])


In [25]:
# split 2d tensors
torch.unbind(two_dim_tensor, dim=1)

(tensor([ 1,  7, 13, 19]),
 tensor([ 2,  8, 14, 20]),
 tensor([ 3,  9, 15, 21]),
 tensor([ 4, 10, 16, 22]),
 tensor([ 5, 11, 17, 23]),
 tensor([ 6, 12, 18, 24]))