<a href="https://colab.research.google.com/github/agu3ro/PyTorch-DL-Linkedin-Learning/blob/main/04_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# Define tensors

x = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]), requires_grad=True)

In [5]:
# Compute gradients

# compute a
a = x - y
print(f"a={a}")

# define the function f
f = z*a

# compute gradients
f.backward()

# print gradient value
print(x.grad)
print(y.grad)
print(z.grad)

a=tensor([1.], grad_fn=<SubBackward0>)
tensor([10.])
tensor([-10.])
tensor([2.])
